name: release-404
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/404/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/reusable.yml
    with:
      APP_NAME: "@app/404"
    secrets: inherit
